import React from "react";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/font-awesome/css/all.min.css";
import { ClerkProvider } from "@clerk/nextjs";
import { TooltipProvider } from "@radix-ui/react-tooltip";
import { DEFAULT_THEME } from "./contexts/theming";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <TooltipProvider>
                <html lang="en">
                    <body className={`${DEFAULT_THEME} ${inter.className}`}>
                        {children}
                    </body>
                </html>
            </TooltipProvider>
        </ClerkProvider>
    );
}
